apiVersion: v1
kind: Service
metadata:
  name: branding-service
  namespace: sharestudio-dev
spec:
  selector:
    app: shar-branding-svc-pod
  ports:
    - port: 8080
      targetPort: brandinghttpport
      name: brandingport